In [1]:


#importing libraries
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report



In [2]:
#import dataset
df = pd.read_csv('train.csv')

# uncomment the line below to drop 
# df = df.drop('battery_power',axis=1)

x, y = df.drop('price_range',axis=1), df['price_range']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=123, stratify=y)

df.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [3]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
import warnings
warnings.filterwarnings('ignore')

gcv = GridSearchCV(LogisticRegression(), {"C":np.logspace(-3,3,7), 
                                          "penalty":["l1","l2"]}).fit(x_train, y_train)
print(gcv.best_params_)

lr = gcv.best_estimator_
y_test_pred = lr.predict(x_test)
y_train_pred = lr.predict(x_train)

lr_acc = accuracy_score(y_test_pred, y_test)

print("Train Set Accuracy: "+str(accuracy_score(y_train_pred,y_train)*100))
print("Test Set Accuracy: "+str(accuracy_score(y_test_pred,y_test)*100))
print("\nConfusion Matrix:\n%s"%confusion_matrix(y_test_pred,y_test))
print("\nClassification Report:\n%s"%classification_report(y_test_pred,y_test))

{'C': 1.0, 'penalty': 'l2'}
Train Set Accuracy: 64.26666666666667
Test Set Accuracy: 63.4

Confusion Matrix:
[[97 25  0  0]
 [27 65 35  1]
 [ 1 30 57 26]
 [ 0  5 33 98]]

Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.80      0.79       122
           1       0.52      0.51      0.51       128
           2       0.46      0.50      0.48       114
           3       0.78      0.72      0.75       136

    accuracy                           0.63       500
   macro avg       0.63      0.63      0.63       500
weighted avg       0.64      0.63      0.64       500



In [4]:
# K-Nearest Neighbors (kNN)
from sklearn.neighbors import KNeighborsClassifier

gcv = GridSearchCV(KNeighborsClassifier(), {"n_neighbors":range(4,20)}).fit(x_train, y_train)

print(gcv.best_params_)

knn = gcv.best_estimator_
y_test_pred1 = knn.predict(x_test)
y_train_pred1 = knn.predict(x_train)

knn_acc = accuracy_score(y_test_pred1,y_test)

print("Train Set Accuracy: "+str(accuracy_score(y_train_pred1,y_train)*100))
print("Test Set Accuracy: "+str(accuracy_score(y_test_pred1,y_test)*100))
print("\nConfusion Matrix:\n%s"%confusion_matrix(y_test_pred1,y_test))
print("\nClassification Report:\n%s"%classification_report(y_test_pred1,y_test))

{'n_neighbors': 9}
Train Set Accuracy: 95.46666666666667
Test Set Accuracy: 91.0

Confusion Matrix:
[[123  14   0   0]
 [  2 104   8   0]
 [  0   7 112   9]
 [  0   0   5 116]]

Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.90      0.94       137
           1       0.83      0.91      0.87       114
           2       0.90      0.88      0.89       128
           3       0.93      0.96      0.94       121

    accuracy                           0.91       500
   macro avg       0.91      0.91      0.91       500
weighted avg       0.91      0.91      0.91       500



In [5]:
# Support Vector Machine (SVM)
from sklearn.svm import SVC

gcv = GridSearchCV(SVC(), {'C': [0.1, 1, 10, 100, 1000]}).fit(x_train, y_train)

print(gcv.best_params_)
svc = gcv.best_estimator_
y_test_pred2 = svc.predict(x_test)
y_train_pred2 = svc.predict(x_train)

svc_acc = accuracy_score(y_test_pred2,y_test)

print("Train Set Accuracy: "+str(accuracy_score(y_train_pred2,y_train)*100))
print("Test Set Accuracy: "+str(accuracy_score(y_test_pred2,y_test)*100))
print("\nConfusion Matrix:\n%s"%confusion_matrix(y_test_pred2,y_test))
print("\nClassification Report:\n%s"%classification_report(y_test_pred2,y_test))

{'C': 100}
Train Set Accuracy: 97.86666666666667
Test Set Accuracy: 96.8

Confusion Matrix:
[[125   4   0   0]
 [  0 115   2   0]
 [  0   6 119   0]
 [  0   0   4 125]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.97      0.98       129
           1       0.92      0.98      0.95       117
           2       0.95      0.95      0.95       125
           3       1.00      0.97      0.98       129

    accuracy                           0.97       500
   macro avg       0.97      0.97      0.97       500
weighted avg       0.97      0.97      0.97       500



In [6]:
# Decision Tree
from sklearn.tree import DecisionTreeClassifier

gcv = GridSearchCV(DecisionTreeClassifier(), {'max_depth': range(1,30), 
                                             'min_samples_split': range(2,8), 
                                             'min_samples_leaf': range(2, 8)}).fit(x_train, y_train)
print(gcv.best_params_)
dt = gcv.best_estimator_
y_test_pred4 = dt.predict(x_test)
y_train_pred4 = dt.predict(x_train)

dt_acc = accuracy_score(y_test_pred4, y_test)

print("Train Set Accuracy: "+str(accuracy_score(y_train_pred4,y_train)*100))
print("Test Set Accuracy: "+str(accuracy_score(y_test_pred4,y_test)*100))
print("\nConfusion Matrix:\n%s"%confusion_matrix(y_test_pred4,y_test))
print("\nClassification Report:\n%s"%classification_report(y_test_pred4,y_test))

{'max_depth': 7, 'min_samples_leaf': 7, 'min_samples_split': 6}
Train Set Accuracy: 92.53333333333333
Test Set Accuracy: 83.6

Confusion Matrix:
[[114  15   0   0]
 [ 11  98  18   0]
 [  0  12  95  14]
 [  0   0  12 111]]

Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.88      0.90       129
           1       0.78      0.77      0.78       127
           2       0.76      0.79      0.77       121
           3       0.89      0.90      0.90       123

    accuracy                           0.84       500
   macro avg       0.84      0.84      0.84       500
weighted avg       0.84      0.84      0.84       500



In [7]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier

gcv = GridSearchCV(RandomForestClassifier(), {'n_estimators': [100, 250, 375, 500],
                                              'criterion': ['gini', 'entropy']}).fit(x_train, y_train)
print(gcv.best_params_)
rf = gcv.best_estimator_
y_test_pred5 = rf.predict(x_test)
y_train_pred5 = rf.predict(x_train)

rf_acc = accuracy_score(y_test_pred5, y_test)

print("Train Set Accuracy: "+str(accuracy_score(y_train_pred5,y_train)*100))
print("Test Set Accuracy: "+str(accuracy_score(y_test_pred5,y_test)*100))
print("\nConfusion Matrix:\n%s"%confusion_matrix(y_test_pred5,y_test))
print("\nClassification Report:\n%s"%classification_report(y_test_pred5,y_test))

{'criterion': 'entropy', 'n_estimators': 500}
Train Set Accuracy: 100.0
Test Set Accuracy: 87.2

Confusion Matrix:
[[120  15   0   0]
 [  5 101  25   0]
 [  0   9  97   7]
 [  0   0   3 118]]

Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.89      0.92       135
           1       0.81      0.77      0.79       131
           2       0.78      0.86      0.82       113
           3       0.94      0.98      0.96       121

    accuracy                           0.87       500
   macro avg       0.87      0.87      0.87       500
weighted avg       0.87      0.87      0.87       500

